# Cheated off of https://github.com/beetbox/beets/blob/master/.travis.yml
matrix:
  include:
    - language: python
      python: 3.7
      env: {TOX_ENV: py37-type}
      install:
        - travis_retry pip install tox
        - travis_retry tox -e $TOX_ENV $SITE_PACKAGES --notest
      script:
        - tox -e $TOX_ENV $SITE_PACKAGES

    - language: python
      python: 3.7
      env: {TOX_ENV: py37-test}
      install:
        - travis_retry pip install tox
        - travis_retry tox -e $TOX_ENV $SITE_PACKAGES --notest
      script:
        - tox -e $TOX_ENV $SITE_PACKAGES

    - language: python
      python: 3.7
      env: {TOX_ENV: py37-cover}
      before_install:
        - travis_retry pip install codecov
      after_success:
        - codecov
      install:
        - travis_retry pip install tox
        - travis_retry tox -e $TOX_ENV $SITE_PACKAGES --notest
      script:
        - tox -e $TOX_ENV $SITE_PACKAGES

    # https://medium.com/faun/configuring-travis-ci-for-angular-application-34afee1715f
    - language: node_js   # https://stackoverflow.com/questions/27644586/
      node_js: 12
      python: 3.7
      cache:
        directories:
          - ./ui/node_modules
      before-install:
        - sudo apt-get -y install python3-pip python-dev
        - sudo pip3 install -U setuptools
        - python3 -V
        - pip3 -V
        - python -V
        - pip -V
      install:
        - sudo pip3 install -r requirements.txt
        - cd ui && npm install
      script:
        - npm run test
