# Cheated off of https://github.com/beetbox/beets/blob/master/.travis.yml
matrix:
  include:
    - language: python
      python: 3.8
      env: {TOX_ENV: py38-type}
      install:
        - "pip install --upgrade pip && pip install -r requirements.txt"
        - travis_retry pip install tox
        - travis_retry tox -vv -e $TOX_ENV --notest
      script:
        - tox -vv -e $TOX_ENV $SITE_PACKAGES

    - language: python
      python: 3.8
      env: {TOX_ENV: py38-test}
      install:
        - "pip install --upgrade pip && pip install -r requirements.txt"
        - travis_retry pip install tox
        - travis_retry tox -vv -e $TOX_ENV --notest
      script:
        - tox -vv -e $TOX_ENV $SITE_PACKAGES

    - language: python
      python: 3.8
      env: {TOX_ENV: py38-cover}
      before_install:
        - travis_retry pip install codecov
      after_success:
        - codecov
      install:
        - "pip install --upgrade pip && pip install -r requirements.txt"
        - travis_retry pip install tox
        - travis_retry tox -vv -e $TOX_ENV --notest
      script:
        - tox -vv -e $TOX_ENV $SITE_PACKAGES

#    # https://medium.com/faun/configuring-travis-ci-for-angular-application-34afee1715f
#    - language: node_js   # https://stackoverflow.com/questions/27644586/
#      node_js: 12
#      cache:
#        directories:
#          - ./node_modules
#      install:
#        - cd ui && npm install
#      script:
#        - ng lint
#        - npm run test-headless
